### ISSUE TITLE
Sympa le TODO file

### ISSUE THREAD

**Issue by Balgor18** [Tachiyoru/Minishell#1]
Pourquoi il est vide ?

**Comment by Shanley-L** [comment]
J'ai pas push ptdr



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : Fcatinau ***@***.***>
Date : 08/02/2023 17:45 (GMT+01:00)
À : Tachiyoru/Minishell ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [Tachiyoru/Minishell] Sympa le TODO file (Issue #1)


Pourquoi il est vide ?
